// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableService.Context;

#nullable disable

namespace TableService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TableService.Models.Models.TableModel", b =>
                {
                    b.Property<string>("TableId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasKey("TableId");

                    b.ToTable("TableItems");

                    b.HasData(
                        new
                        {
                            TableId = "T001",
                            Available = true,
                            Capacity = 4,
                            Location = "Window"
                        },
                        new
                        {
                            TableId = "T002",
                            Available = false,
                            Capacity = 2,
                            Location = "Corner"
                        },
                        new
                        {
                            TableId = "T003",
                            Available = true,
                            Capacity = 6,
                            Location = "Center"
                        },
                        new
                        {
                            TableId = "T004",
                            Available = false,
                            Capacity = 6,
                            Location = "Balcony"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
